"""
VoBee Backend API
Czech Financial Education Platform
"""
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional, List
import uvicorn

app = FastAPI(
    title="VoBee API",
    description="Backend API for VoBee - Czech Financial Education App",
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Models
class ChatRequest(BaseModel):
    message: str
    user_id: Optional[str] = None


class ChatResponse(BaseModel):
    response: str
    audio_url: Optional[str] = None
    avatar_animation: Optional[str] = None


class FinancialTip(BaseModel):
    id: int
    title: str
    content: str
    category: str


# Sample responses for financial queries
FINANCIAL_RESPONSES = {
    "investice": "Pro začátek doporučuji diverzifikované ETF fondy. Začněte s malou částkou a postupně ji zvyšujte.",
    "krypto": "Kryptoměny jsou velmi volatilní. Investujte pouze prostředky, které si můžete dovolit ztratit.",
    "rozpočet": "Zkuste pravidlo 50/30/20: 50% na potřeby, 30% na přání a 20% na úspory.",
    "dluhy": "Prioritně splácejte dluhy s nejvyšším úrokem (metoda laviny).",
    "default": "Jsem váš finanční asistent VoBee. Mohu vám pomoci s investicemi, rozpočtem, kryptoměnami nebo dluhy."
}

FINANCIAL_TIPS = [
    FinancialTip(id=1, title="Nouzový fond", content="Mějte úspory na 3-6 měsíců výdajů.", category="savings"),
    FinancialTip(id=2, title="Složený úrok", content="Čas je váš nejlepší přítel při investování.", category="investing"),
    FinancialTip(id=3, title="Diverzifikace", content="Nevsázejte vše na jednu kartu.", category="investing"),
]


@app.get("/")
async def root():
    """Root endpoint"""
    return {"message": "VoBee API is running", "version": "1.0.0"}


@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {"status": "healthy"}


@app.post("/api/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    Process chat message and return response with optional TTS audio
    """
    message = request.message.lower()
    
    response_text = FINANCIAL_RESPONSES["default"]
    for keyword, response in FINANCIAL_RESPONSES.items():
        if keyword in message:
            response_text = response
            break
    
    return ChatResponse(
        response=response_text,
        audio_url=None,  # Would be generated by TTS service
        avatar_animation="speaking"
    )


@app.get("/api/tips", response_model=List[FinancialTip])
async def get_tips(category: Optional[str] = None):
    """
    Get financial tips, optionally filtered by category
    """
    if category:
        return [tip for tip in FINANCIAL_TIPS if tip.category == category]
    return FINANCIAL_TIPS


@app.get("/api/tips/{tip_id}", response_model=FinancialTip)
async def get_tip(tip_id: int):
    """
    Get a specific financial tip by ID
    """
    for tip in FINANCIAL_TIPS:
        if tip.id == tip_id:
            return tip
    raise HTTPException(status_code=404, detail="Tip not found")


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
